### ISSUE TITLE
Address Dongles via the Serial Number

### ISSUE THREAD

**Issue by Skaugent** [roger-/pyrtlsdr#61]
Hello,

is it possible to address multiple dongles with their own serial number ? If this feature is not added yet, how difficult is it to add it from the librtlsdr library ?

regards

Skaugent

**Comment by nocarryr** [comment]
@Skaugent I apologize for the delay.  Trying to catch up on things here.

In looking through the [librtlsdr](https://github.com/librtlsdr/librtlsdr) source code, it does appear to be fairly simple to add this feature as there is a function call for [`rtlsdr_get_index_by_serial`](https://github.com/librtlsdr/librtlsdr/blob/master/include/rtl-sdr.h#L58-L67).

The implementation within pyrtlsdr could be done, but since the `RtlSdr` class is initialized by `device_index`, it may not be as straightforward as:
```python
sdr = Rtlsdr(my_dongle_serial)
```

It may be better suited as either a class method or a standalone function which would gather the detected device information and return a `dict` of `{device_serial:device_index}` (or similar).

Would that be a suitable approach?
